import type { Session } from "../types/liveSessions";


export const sessions: Session[] = [
  {
    id: "SE5801",
    customer: "Amit Bose",
    vehicle: "Tata Nexon EV",
    station: "MG Road Fast Char...",
    stationFull: "MG Road Fast Charge Hub",
    energy: "18.4 kWh",
    duration: "38 min",
    cost: "₹460",
    status: "Active",
  },
  {
    id: "SE5802",
    customer: "Divya Nair", 
    vehicle: "MG ZS EV",
    station: "BKC EV Plaza",
    stationFull: "BKC EV Plaza",
    energy: "42.1 kWh",
    duration: "57 min",
    cost: "₹1052",
    status: "Active",
  },
  {
    id: "SE5803",
    customer: "Rohan Gupta",
    vehicle: "Hyundai Kona",
    station: "Connaught Place H...",
    stationFull: "Connaught Place Hub",
    energy: "28.6 kWh",
    duration: "72 min",
    cost: "₹715",
    status: "Active",
  },
  {
    id: "SE5804",
    customer: "Meena Krishnan",
    vehicle: "Tata Tigor EV",
    station: "Salt Lake EV Point",
    stationFull: "Salt Lake EV Point",
    energy: "35.2 kWh",
    duration: "92 min",
    cost: "₹880",
    status: "Completed",
  },
  {
    id: "SE5805",
    customer: "Suresh Pillai",
    vehicle: "Ola S1 Pro",
    station: "Anna Nagar Station",
    stationFull: "Anna Nagar Station",
    energy: "12.8 kWh",
    duration: "110 min",
    cost: "₹320",
    status: "Completed",
  },
  {
    id: "SE5806",
    customer: "Kavitha Reddy",
    vehicle: "Bajaj Chetak",
    station: "Koregaon Park Fast...",
    stationFull: "Koregaon Park Fast Charge",
    energy: "8.4 kWh",
    duration: "45 min",
    cost: "₹210",
    status: "Failed",
  },
];
