import type { Station } from "../types/stations";


export const stations: Station[] = [
  {
    id: "ST001",
    name: "MG Road Fast Charge Hub",
    location: "MG Road, Bengaluru",
    vendor: "GreenCharge India",
    chargers: { total: 8, available: 5, busy: 2, offline: 1 },
    utilization: 25,
    status: "Available",
  },
  { 
    id: "ST002",
    name: "BKC EV Plaza",
    location: "BKC, Mumbai",
    vendor: "ChargePoint Networks",
    chargers: { total: 12, available: 3, busy: 8, offline: 1 },
    utilization: 67,
    status: "Charging",
  },
  {
    id: "ST003",
    name: "Cyber Hub Station",
    location: "Cyber Hub, Gurgaon",
    vendor: "EcoVolt Solutions",
    chargers: { total: 6, available: 0, busy: 0, offline: 6 },
    utilization: 0,
    status: "Offline",
  },
  {
    id: "ST004",
    name: "Connaught Place Hub",
    location: "CP, New Delhi",
    vendor: "ChargePoint Networks",
    chargers: { total: 10, available: 4, busy: 5, offline: 1 },
    utilization: 50,
    status: "Charging",
  },
  {
    id: "ST005",
    name: "Koregaon Park Fast Charge",
    location: "Koregaon Park, Pune",
    vendor: "Zap Electric",
    chargers: { total: 4, available: 4, busy: 0, offline: 0 },
    utilization: 0,
    status: "Available",
  },
  {
    id: "ST006",
    name: "Hitech City Hub",
    location: "Hitech City, Hyderabad",
    vendor: "NexGen Charge",
    chargers: { total: 6, available: 0, busy: 0, offline: 6 },
    utilization: 0,
    status: "Maintenance",
  },
  {
    id: "ST007",
    name: "Salt Lake EV Point",
    location: "Salt Lake, Kolkata",
    vendor: "EcoVolt Solutions",
    chargers: { total: 5, available: 3, busy: 2, offline: 0 },
    utilization: 40,
    status: "Charging",
  },
  {
    id: "ST008",
    name: "Anna Nagar Station",
    location: "Anna Nagar, Chennai",
    vendor: "GreenCharge India",
    chargers: { total: 7, available: 6, busy: 1, offline: 0 },
    utilization: 14,
    status: "Available",
  },
];
